# Generated by Django 3.2.9 on 2021-12-04 23:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profle',
        ),
        migrations.RenameField(
            model_name='profle',
            old_name='bioghraphy',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='profle',
            old_name='created',
            new_name='create',
        ),
    ]
